### ISSUE TITLE
Deployment problem

### ISSUE THREAD

**Issue by KristaTheCoder** [jovotech/jovo-templates#16]
Alexa Audio Player
jovo version 1.1.11

After running :
$ jovo init alexaSkill
$ jovo build
$ jovo deploy

I get the following error: 
Updating Alexa Skill project for ASK profile default

Cannot find module " /home/ ... /platforms/alexaSkill/models/en-US.json"

There is a skill.json file and an en-US.json file it's just in a different folder than the one it's looking for. 

When I run jovo run it also says it cannot find then index.js file even though one exists.

**Comment by jankoenig** [comment]
Hi @KristaTheCoder, in which folder are you with the command line when you're executing those commands?

After `$ jovo new <directory> --template alexa/audioplayer`, did you go into the created directory with `$ cd <directory>`?

**Comment by KristaTheCoder** [comment]
Here's a screenshot with my terminal. 

![screenshot from 2018-07-08 12-43-39](https://user-images.githubusercontent.com/15697505/42423274-a7b9103e-82ac-11e8-8bb9-491407129869.png)

**Comment by jankoenig** [comment]
Could you show me how your `models` the root folder and your `platforms/alexaSkill` folder look like?

**Comment by KristaTheCoder** [comment]
Hi @jankoenig somehow I got a typo into mulocal interaction model which caused the failure. The Github repo works fine, my mistake.

Krista
