### ISSUE TITLE
 Cannot find module 'alexa/apl/javascript/src/apl/main'

### ISSUE THREAD

**Issue by jakolar** [jovotech/jovo-templates#41]
Thank you for the Jovo template, I believe that there is a problem in the template path. After the first run, I received this error: "Cannot find module 'alexa/apl/javascript/src/apl/main'" 

The problem I believe is in the path of in the LAUNCH Intent:

"document: require(`alexa/apl/javascript/src/apl/main`), // Plain "Hello World" template"

This path removest the problem: 

"document: require(`./apl/main.json`), // Plain "Hello World" template"

**Comment by jankoenig** [comment]
Thank you @jakolar! Fixed
