### ISSUE TITLE
Add jovo-platform-googleassistantconv to the sample.test.js file

### ISSUE THREAD

**Issue by nathandrew** [jovotech/jovo-templates#56]
The template does not require the correct library:  `jovo-platform-googleassistant` should be `jovo-platform-googleassistantconv`.  

https://github.com/jovotech/jovo-templates/blob/master/google/conversational-actions-hello-world/javascript/test/sample.test.js#L4

**Comment by aswetlow** [comment]
Thanks @nathandrew  
Fixed it.
