### ISSUE TITLE
Debugger not working with Google Conversational template

### ISSUE THREAD

**Issue by mig82** [jovotech/jovo-templates#60]
Hi. I'm not sure what's wrong here, but the debugger does not seem to be working with the Google conversational template. 
I created the project like this:

```
jovo new --template google-conversational-actions-helloworld
```
And didn't make any modifications.

I've tried a number of times with different locales, switching back to v1, and both with speaker and phone. It just doesn't answer.

<img width="1041" alt="image" src="https://user-images.githubusercontent.com/10434613/106086021-99f94f80-6121-11eb-8b14-343fbcc4b558.png">

The logs show there is a response. But it just doesn't come up in the debugger.

**Comment by mig82** [comment]
Here are the plugins I'm using.

```
$ jovo update

 jovo update: Updates the Jovo modules in project to latest versions.
   >> Learn more: https://jovo.tech/docs/cli/update

Jovo packages of current project:
  jovo-db-filedb : 3.3.1
  jovo-framework : 3.3.1
  jovo-platform-alexa : 3.3.1
  jovo-platform-googleassistantconv : 3.3.1
  jovo-plugin-debugger : 3.3.1


All packages are already up to date!
```

**Comment by jankoenig** [comment]
Hi @mig82, thanks for flagging. We're currently working on this!

**Comment by jankoenig** [comment]
Hey @mig82, can you run `jovo update` and try again? Fixed by @aswetlow with this PR: https://github.com/jovotech/jovo-framework/pull/890

**Comment by mig82** [comment]
Hi @jankoenig. I've run `jovo update`.

<img width="775" alt="image" src="https://user-images.githubusercontent.com/10434613/106582802-ad068800-6544-11eb-8968-0ffd0f2f030f.png">

Then re-ran `jovo build` just in case.
Then ran `jovo run` and now I notice the new **"Google Assistant Conversational Actions"** options in the debugger.
<img width="284" alt="image" src="https://user-images.githubusercontent.com/10434613/106583349-4afa5280-6545-11eb-9b7a-fefbef6dd4c7.png">

I tried them and they work well :)

<img width="596" alt="image" src="https://user-images.githubusercontent.com/10434613/106583756-bc3a0580-6545-11eb-9b75-6ea1960704b2.png">

I'm closing the ticket.
Thank you!
